version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: 'bitnami/kafka:2.5.0'
    hostname: kafka1
    container_name: kafka1
    ports:
      - '19092:19092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,LISTENER_DOCKER_INTERNAL://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:19092,LISTENER_DOCKER_INTERNAL://:19093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
    depends_on:
      - zookeeper

  kafka-2:
    image: 'bitnami/kafka:2.5.0'
    hostname: kafka2
    container_name: kafka2
    ports:
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,LISTENER_DOCKER_INTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092,LISTENER_DOCKER_INTERNAL://:29093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
    depends_on:
      - zookeeper
